# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\code\assign\chinese\erppython\erpInfo\erpteam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeamMainWindow(object):
    def setupUi(self, TeamMainWindow):
        TeamMainWindow.setObjectName("TeamMainWindow")
        TeamMainWindow.resize(553, 484)
        self.centralwidget = QtWidgets.QWidget(TeamMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.exportdata = QtWidgets.QPushButton(self.centralwidget)
        self.exportdata.setGeometry(QtCore.QRect(1100, 60, 91, 31))
        self.exportdata.setObjectName("exportdata")
        self.exporthint = QtWidgets.QLabel(self.centralwidget)
        self.exporthint.setGeometry(QtCore.QRect(220, 130, 251, 31))
        self.exporthint.setText("")
        self.exporthint.setObjectName("exporthint")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(130, 410, 75, 24))
        self.confirmButton.setObjectName("confirmButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(340, 410, 75, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(110, 11, 401, 371))
        self.listWidget.setObjectName("listWidget")
        TeamMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TeamMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 553, 22))
        self.menubar.setObjectName("menubar")
        TeamMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TeamMainWindow)
        self.statusbar.setObjectName("statusbar")
        TeamMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TeamMainWindow)
        QtCore.QMetaObject.connectSlotsByName(TeamMainWindow)

    def retranslateUi(self, TeamMainWindow):
        _translate = QtCore.QCoreApplication.translate
        TeamMainWindow.setWindowTitle(_translate("TeamMainWindow", "MainWindow"))
        self.exportdata.setText(_translate("TeamMainWindow", "导出"))
        self.confirmButton.setText(_translate("TeamMainWindow", "确定"))
        self.cancelButton.setText(_translate("TeamMainWindow", "取消"))
