# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\code\assign\chinese\erppython\erpInfo\erp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 272)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 71, 31))
        self.label.setObjectName("label")
        self.selectfilepath = QtWidgets.QPushButton(self.centralwidget)
        self.selectfilepath.setGeometry(QtCore.QRect(460, 90, 31, 31))
        self.selectfilepath.setObjectName("selectfilepath")
        self.exportdata = QtWidgets.QPushButton(self.centralwidget)
        self.exportdata.setGeometry(QtCore.QRect(1100, 60, 91, 31))
        self.exportdata.setObjectName("exportdata")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(80, 30, 141, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 121, 31))
        self.label_2.setObjectName("label_2")
        self.editFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.editFilePath.setGeometry(QtCore.QRect(110, 90, 341, 31))
        self.editFilePath.setObjectName("editFilePath")
        self.buttonnexportfile = QtWidgets.QPushButton(self.centralwidget)
        self.buttonnexportfile.setGeometry(QtCore.QRect(260, 173, 141, 31))
        self.buttonnexportfile.setObjectName("buttonnexportfile")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 30, 51, 31))
        self.label_3.setObjectName("label_3")
        self.editTeam = QtWidgets.QLineEdit(self.centralwidget)
        self.editTeam.setGeometry(QtCore.QRect(290, 30, 211, 31))
        self.editTeam.setObjectName("editTeam")
        self.exporthint = QtWidgets.QLabel(self.centralwidget)
        self.exporthint.setGeometry(QtCore.QRect(220, 130, 251, 31))
        self.exporthint.setText("")
        self.exporthint.setObjectName("exporthint")
        self.buttonTeam = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTeam.setGeometry(QtCore.QRect(510, 30, 141, 31))
        self.buttonTeam.setObjectName("buttonTeam")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "时间:"))
        self.selectfilepath.setText(_translate("MainWindow", "..."))
        self.exportdata.setText(_translate("MainWindow", "导出"))
        self.label_2.setText(_translate("MainWindow", "文件保存路径:"))
        self.buttonnexportfile.setText(_translate("MainWindow", "导出文件"))
        self.label_3.setText(_translate("MainWindow", "班组:"))
        self.buttonTeam.setText(_translate("MainWindow", "选择班组"))
